module.exports = {

    id : (text) => `Es necesario el ID del y/o para ${text}.`,
    numeric :  'Este campo debe ser numérico.',
    position: 'Es necesario el cargo que desempeña(ó) en su trabajo.',
    dateStart: 'Es necesario una fecha de inicio.',
    dateEnd: 'Es necesario una fecha de finalización.',
    dateExpedition: 'Es necesario una fecha de expedición.',
    date: (text) => `Es necesario una fecha para ${text}.`,
    time: (text) => `Es necesario la hora para ${text}.`,
    type: (text) => `Es necesario el tipo para ${text}.`,
    only: (...type) => `Solamente se admiten ${type}`,
    validationData: 'Lo sentimos, necesitamos algunos datos obligatorios.',
    successUpdate: (text) => `${text.charAt(0).toUpperCase() + text.slice(1)} actualizado(a) satisfactoriamente.`,
    successCreate: (text) => `${text.charAt(0).toUpperCase() + text.slice(1)} creado(a) satisfactoriamente.`,
    successDelete: (text) => `${text.charAt(0).toUpperCase() + text.slice(1)} eliminado(a) satisfactoriamente.`,
    duplicateElement:  'Lo sentimos, el elemento que intenta crear ya se encuentra registrado(a).',
    notFoundElement:  'Lo sentimos, los datos enviados no coinciden con nuestros registros.',
    description: 'Es necesario una descripción.',
    name: (text) =>  `Es necesario un nombre del y/o para ${text}.`,
    downloadDocument: (url) => `http://35.175.241.103:8081/certifications/download/${(url).split('/')[5]}`,
    notAvailable: (text) => `Lo sentimos, la ${text} seleccionada no esta disponible.`,
    incorrectFormat: (text) => `Lo sentimos, el formato de ${text} es incorrecto.`,
    fileElement: (text) => `Es necesario un(a) ${text}.`,
    title: (text) => `Es necesario un titulo para ${text}`,
    day: (text) => `Es necesario un titulo para ${text}`,
    place: (text) => `Es necesario un titulo para ${text}`,
    category: (text) => `Es necesario categoria(s) para ${text}`,
    participants: `Se necesita una cantidad máxima de participantes al evento.`,
    add: `Añadido satisfactoriamente.`,
    removed: `Removido satisfactoriamente.`,
    exceeded: `Lo sentimos ha superado el máximo permitido.`,
    reunion: `Agendar reunión.`,
    confirmation: `Confirmación de reunión`,
    challengeValidation: `Validación de reto`,
    correctState: `Felicitaciones`,
    incorrectState: `Lo sentimos`,
    messageCorrectState: `El siguiente reto que completó ha sido aprobado, siéntase alegre.`,
    noComment: `Sin comentarios.`,
    messageIncorrectState: `El siguiente reto presenta algunas correcciones, por favor revisalas.`,
    messageConfirmationEmisor: (emisor, receptor, date, time) => `Hola estimado ${emisor}, te informamos que ${receptor} accedió ha tener una reunión el día ${date} a la(s) ${time}.`,
    messageConfirmationReceptor: (emisor, receptor, date, time) => `Hola estimado ${receptor}, gracias por confirmar reunión tu con ${emisor} el día ${date} a la(s) ${time}.`,
    messageRejectionEmisor: (emisor, receptor, date, time) => `Hola estimado ${emisor}, te informamos que lamentablemente ${receptor} no accedió ha tener una reunión el dia ${date} a la(s) ${time}.`,
    messageRejectionReceptor: (emisor, receptor, date, time) => `Hola estimado ${receptor}, lamentamos que no pudiera acceder ha tener una reunión el día ${date} a la(s) ${time}.`,
    manProfileImage: `https://techie-exitum.s3-us-west-1.amazonaws.com/imagenes/email-images/man_profile.png`,
    succesful_validation: `Se validó satisfactoriamente el reto.`,
    message_event: (usuario, status) => `Hola ${usuario}! Te informamos que tu solicitud de participacion en el siguiente evento, ${status}. Gracias por participar.`,
    eventParticipation: (evento) => `Participación en el evento ${evento}.`,
    email: (text) => `Es necesario un correo electronico para el ${text}.`,
    password: (text) => `Es necesario una contraseña para el ${text}.`,
    failLogin:  `Credenciales incorrectas.`,
    adminNotExist: `No existe esta cuenta.`,
    duplicateEmail: `El correo electrónico ya se encuentra registrado.`,
    tip: `Es necesario el nombre del tip`,
    tokenNotProvided: `Lo sentimos no cuenta con los permisos necesarios.`,
    failedTokenVerification: `Token no válido.`,
    failedTokenExpiration: `Token expirado.`,
    requireImage: `Se necesita una imagen.`,
    messageToReceptor: (name) => `¡Hola ${name}! Te informamos que tienes reuniones pendientes por aceptar o cancelar. Por favor revisa tu bandeja de entrada en Exitum.pe`,
    messageToEmisor: (receptor, name) => `¡Hola ${name}! Te informamos que tu reunión con ${receptor} aún esta pendiente por ser aceptada.`,

}